import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  inputPadrao: {
    borderWidth: 1,
    borderColor: "#B7B7A4",
    backgroundColor: "#F9F9F9",
    padding: 12,
    borderRadius: 8,
    marginBottom: 14,
    color: "#023D2E",
  },
  formularioContainer: {
    flex: 1,
    backgroundColor: "#F5FAF6",
    padding: 16,
  },
  tituloBloco: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#023D2E",
    marginBottom: 10,
  },
  listaIngrediente: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  secoesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
  },
  botaoSecao: {
    backgroundColor: "#eee",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  botaoSecaoAtivo: {
    backgroundColor: "#3C6E47",
    borderColor: "#3C6E47",
  },
  textoSecao: {
    fontSize: 13,
    color: "#333",
  },
  textoSecaoAtivo: {
    color: "#fff",
    fontWeight: "bold",
  },
  botaoAdicionar: {
    backgroundColor: "#3C6E47",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginBottom: 12,
    alignItems: "center",
  },
  textoBotao: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 14,
  },
  secaoTitulo: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#3C6E47",
    marginTop: 10,
    marginBottom: 4,
  },
  listaItemTexto: {
    fontSize: 14,
    marginLeft: 8,
    marginBottom: 4,
  },
  pickerHora: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    padding: 10,
    backgroundColor: "#f9f9f9",
    marginBottom: 16,
  },
  categoriaContainer: {
    marginBottom: 20,
  },
  tagCategoria: {
    backgroundColor: "#DDB892",
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 12,
    marginRight: 6,
    marginBottom: 6,
  },
  tagCategoriaSelecionada: {
    backgroundColor: "#3C6E47",
  },
  tagCategoriaTexto: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 13,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    backgroundColor: "#fff",
  },
  blocoResumo: {
    backgroundColor: "#F4F4F4",
    padding: 14,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  tituloResumo: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#023D2E",
    marginBottom: 8,
  },
  blocoPadrao: {
    backgroundColor: "#F4F4F4",
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#ccc",
  },
  tituloSessao: {
    fontSize: 16,
    fontWeight: "bold",
    marginTop: 16,
    marginBottom: 8,
    color: "#2E2E2E",
  },
  botaoExcluir: {
    backgroundColor: "#eee",
    padding: 8,
    borderRadius: 4,
  },
  textoBotaoExcluir: {
    color: "red",
    fontSize: 16,
  },
});
