import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    alignItems: "center",
  },
  modal: {
    width: "92%",
    maxHeight: "92%",
    backgroundColor: "#FAFDFB",
    borderRadius: 20,
    padding: 22,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 8,
  },
  titulo: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#2E4F36",
    marginBottom: 14,
    textAlign: "center",
  },
  input: {
    backgroundColor: "#F0F4F2",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    marginBottom: 10,
    fontSize: 15,
    borderWidth: 1,
    borderColor: "#D8E4DC",
    color: "#333",
  },
  botaoPublicar: {
    backgroundColor: "#3C6E47", // verde principal do projeto
    paddingVertical: 14,
    borderRadius: 10,
    marginTop: 16,
    alignItems: "center",
  },
  textoBotaoPublicar: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    textAlign: "center",
  },
  botaoFechar: {
    marginTop: 10,
    alignItems: "center",
    backgroundColor: "#E8EFE8",
    paddingVertical: 10,
    borderRadius: 10,
  },
  textoBotao: {
    color: "#2E4F36",
    fontWeight: "600",
    fontSize: 15,
  },
  headerUsuario: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    gap: 12,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#ccc",
  },
  nomeUsuario: {
    fontWeight: "bold",
    fontSize: 15,
    color: "#2c2c2c",
  },
  tipoUsuario: {
    fontSize: 13,
    color: "#666",
  },
  rodape: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 12,
    marginTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 20,
  },

  botaoAcao: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  erroContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
   erro: {
    color: "#D32F2F",
    fontSize: 16,
    textAlign: "center",
    marginTop: 10,
    marginBottom: 8,
  },
  botaoAtualizar: {
    backgroundColor: "#3C6E47",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
    height: 48,
    justifyContent: "center",
    width: "100%",
    marginTop: 15,
  },
  botaoCancelar: {
    marginTop: 10,
    alignItems: "center",
    backgroundColor: "#E8EFE8",
    paddingVertical: 10,
    borderRadius: 10,
  },
   atualizarBotaoTexto: {
    color: 'white',
    fontWeight: 'bold',
  },
   cancelarTexto: {
    color: "#2E4F36",
    fontWeight: "600",
    fontSize: 15,
  },
});
